### ISSUE TITLE
compiling nginx fails

### ISSUE THREAD

**Issue by p-doyle** [chobits/ngx_http_proxy_connect_module#14]
I receive this error when running the make command:
```

/home/ubuntu/nginx-1.12.1/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:171:7: error: ‘ngx_http_null_variable’ undeclared here (not in a function)
       ngx_http_null_variable
       ^
objs/Makefile:1765: recipe for target 'objs/addon/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.o' failed
```
I believe this is due to the most recent commit as I was able to compile it yesterday with no issues...

**Comment by chobits** [comment]
thanks for ur report, let me check.

**Comment by chobits** [comment]
This regression is introduced by https://github.com/chobits/ngx_http_proxy_connect_module/pull/13. will give a new patch to fix soon

**Comment by chobits** [comment]
fixed in https://github.com/chobits/ngx_http_proxy_connect_module/pull/15.

**Comment by chobits** [comment]
Think it resolved.

I am closing this issue. If u have any question, feel free to reopen it.
