### ISSUE TITLE
Build errors on 1.12.2

### ISSUE THREAD

**Issue by AndreiG6** [chobits/ngx_http_proxy_connect_module#23]
Hello,

I'm running into the following errors when trying to build with Nginx 1.12.2. The same configure line works fine for 1.12.1.

Configure:
`./configure --add-module=/usr/local/src/nginx/modules/lua-nginx-module --add-module=/usr/local/src/nginx/modules/ngx_http_proxy_connect_module --prefix=/usr/share/nginx --sbin-path=/usr/sbin/nginx --modules-path=/usr/lib64/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --http-client-body-temp-path=/var/lib/nginx/tmp/client_body --http-proxy-temp-path=/var/lib/nginx/tmp/proxy --http-fastcgi-temp-path=/var/lib/nginx/tmp/fastcgi --http-uwsgi-temp-path=/var/lib/nginx/tmp/uwsgi --http-scgi-temp-path=/var/lib/nginx/tmp/scgi --pid-path=/run/nginx.pid --lock-path=/run/lock/subsys/nginx --user=nginx --group=nginx --with-file-aio --with-ipv6 --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_xslt_module=dynamic --with-http_image_filter_module=dynamic --with-http_geoip_module=dynamic --with-http_sub_module --with-http_dav_module --with-http_flv_module --with-http_mp4_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_random_index_module --with-http_secure_link_module --with-http_degradation_module --with-http_slice_module --with-http_stub_status_module --with-http_perl_module=dynamic --with-mail=dynamic --with-mail_ssl_module --with-pcre --with-pcre-jit --with-stream=dynamic --with-stream_ssl_module --with-google_perftools_module --with-debug --with-cc-opt='-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' --with-ld-opt='-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-E'`

Errors:

```
In file included from src/core/ngx_core.h:58:0,
                 from /usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:7:
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c: In function ‘ngx_http_proxy_connect_upstream_handler’:
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:734:22: error: ‘ngx_http_request_t’ has no member named ‘connect_host’
                    &r->connect_host, &r->connect_port);
                      ^
src/core/ngx_log.h:93:48: note: in definition of macro ‘ngx_log_debug’
         ngx_log_error_core(NGX_LOG_DEBUG, log, __VA_ARGS__)
                                                ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:732:5: note: in expansion of macro ‘ngx_log_debug2’
     ngx_log_debug2(NGX_LOG_DEBUG_HTTP, c->log, 0,
     ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:734:40: error: ‘ngx_http_request_t’ has no member named ‘connect_port’
                    &r->connect_host, &r->connect_port);
                                        ^
src/core/ngx_log.h:93:48: note: in definition of macro ‘ngx_log_debug’
         ngx_log_error_core(NGX_LOG_DEBUG, log, __VA_ARGS__)
                                                ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:732:5: note: in expansion of macro ‘ngx_log_debug2’
     ngx_log_debug2(NGX_LOG_DEBUG_HTTP, c->log, 0,
     ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c: In function ‘ngx_http_proxy_connect_check_broken_connection’:
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1027:33: error: ‘ngx_http_request_t’ has no member named ‘connect_host’
                    ev->write, &r->connect_host, &r->connect_port);
                                 ^
src/core/ngx_log.h:93:48: note: in definition of macro ‘ngx_log_debug’
         ngx_log_error_core(NGX_LOG_DEBUG, log, __VA_ARGS__)
                                                ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1025:5: note: in expansion of macro ‘ngx_log_debug3’
     ngx_log_debug3(NGX_LOG_DEBUG_HTTP, ev->log, 0,
     ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1027:51: error: ‘ngx_http_request_t’ has no member named ‘connect_port’
                    ev->write, &r->connect_host, &r->connect_port);
                                                   ^
src/core/ngx_log.h:93:48: note: in definition of macro ‘ngx_log_debug’
         ngx_log_error_core(NGX_LOG_DEBUG, log, __VA_ARGS__)
                                                ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1025:5: note: in expansion of macro ‘ngx_log_debug3’
     ngx_log_debug3(NGX_LOG_DEBUG_HTTP, ev->log, 0,
     ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c: In function ‘ngx_http_proxy_connect_handler’:
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1190:39: error: ‘ngx_http_request_t’ has no member named ‘connect_port_n’
             if ((ports[i][1] == 0 && r->connect_port_n == ports[i][0])
                                       ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1191:37: error: ‘ngx_http_request_t’ has no member named ‘connect_port_n’
                 || (ports[i][0] <= r->connect_port_n && r->connect_port_n <= ports[i][1]))
                                     ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1191:58: error: ‘ngx_http_request_t’ has no member named ‘connect_port_n’
                 || (ports[i][0] <= r->connect_port_n && r->connect_port_n <= ports[i][1]))
                                                          ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1199:14: error: ‘ngx_http_request_t’ has no member named ‘connect_port_n’
         if (r->connect_port_n == 443 || r->connect_port_n == 563) {
              ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1199:42: error: ‘ngx_http_request_t’ has no member named ‘connect_port_n’
         if (r->connect_port_n == 443 || r->connect_port_n == 563) {
                                          ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1230:20: error: ‘ngx_http_request_t’ has no member named ‘connect_host’
     url.url.len = r->connect_host.len;
                    ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1231:21: error: ‘ngx_http_request_t’ has no member named ‘connect_host’
     url.url.data = r->connect_host.data;
                     ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1232:25: error: ‘ngx_http_request_t’ has no member named ‘connect_port_n’
     url.default_port = r->connect_port_n;
                         ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1263:30: error: ‘ngx_http_request_t’ has no member named ‘connect_host’
         u->resolved->host = r->connect_host;
                              ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1264:42: error: ‘ngx_http_request_t’ has no member named ‘connect_port_n’
         u->resolved->port = (in_port_t) r->connect_port_n;
                                          ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1275:18: error: ‘ngx_http_request_t’ has no member named ‘connect_host’
     temp.name = r->connect_host;
                  ^
In file included from src/core/ngx_core.h:58:0,
                 from /usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:7:
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1287:62: error: ‘ngx_http_request_t’ has no member named ‘connect_host’
                       "no resolver defined to resolve %V", &r->connect_host);
                                                              ^
src/core/ngx_log.h:86:67: note: in definition of macro ‘ngx_log_error’
     if ((log)->log_level >= level) ngx_log_error_core(level, log, __VA_ARGS__)
                                                                   ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1291:19: error: ‘ngx_http_request_t’ has no member named ‘connect_host’
     rctx->name = r->connect_host;
                   ^
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c: In function ‘ngx_http_proxy_connect’:
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:1395:9: error: ‘ngx_http_core_loc_conf_t’ has no member named ‘accept_connect’
     clcf->accept_connect = 1;
         ^
make[1]: *** [objs/addon/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/usr/local/src/nginx/nginx-1.12.2'
make: *** [build] Error 2
```

**Comment by chobits** [comment]
hi @AndreiG6 

>In file included from src/core/ngx_core.h:58:0,
>                 from /usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:7:
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c: In function ‘ngx_http_proxy_connect_upstream_handler’:
/usr/local/src/nginx/modules/ngx_http_proxy_connect_module/ngx_http_proxy_connect_module.c:734:22: error: ‘ngx_http_request_t’ has no member named ‘connect_host’

It seems that proxy_connect.patch is not patched to nginx-1.12.2.

With patching proxy_connect.patch, I can compile nginx-1.12.2 successfully.

**Comment by AndreiG6** [comment]
Ah, you're totally right! Sorry for the mixup, the patch wasn't being executed in my build script. It works fine with 1.12.2, thanks for your time!

**Comment by Whirlwind** [comment]
I have same problem. nginx `1.13.12`:
```
$ patch -p1 < proxy_connect_1014.patch
patch: **** Only garbage was found in the patch input.
```

Error:
```
$ ./configure --add-module=ngx_http_proxy_connect_module-master

....

ngx_http_proxy_connect_module-master/ngx_http_proxy_connect_module.c:1350:41: error:
      no member named 'connect_port_n' in 'struct ngx_http_request_s'
            if ((ports[i][1] == 0 && r->connect_port_n == ports[i][0])
                                     ~  ^
ngx_http_proxy_connect_module-master/ngx_http_proxy_connect_module.c:1351:39: error:
      no member named 'connect_port_n' in 'struct ngx_http_request_s'
                || (ports[i][0] <= r->connect_port_n && r->connect_port_n <= p...
                                   ~  ^
ngx_http_proxy_connect_module-master/ngx_http_proxy_connect_module.c:1351:60: error:
      no member named 'connect_port_n' in 'struct ngx_http_request_s'
                || (ports[i][0] <= r->connect_port_n && r->connect_port_n <= p...
                                                        ~  ^
ngx_http_proxy_connect_module-master/ngx_http_proxy_connect_module.c:1359:16: error:
      no member named 'connect_port_n' in 'struct ngx_http_request_s'
        if (r->connect_port_n == 443 || r->connect_port_n == 563) {
            ~  ^
ngx_http_proxy_connect_module-master/ngx_http_proxy_connect_module.c:1359:44: error:
      no member named 'connect_port_n' in 'struct ngx_http_request_s'
        if (r->connect_port_n == 443 || r->connect_port_n == 563) {
                                        ~  ^
```

**Comment by Whirlwind** [comment]
Sorry, I get a blank patch file....
