### PR TITLE
fixed compilation error for 'undefined ngx_http_null_variable'

### PR DESCRIPTION
**Pull request by chobits**
This regression is introduced by https://github.com/chobits/ngx_http_proxy_connect_module/pull/13.
Thanks to github user @p-doyle.

### CODE REVIEW

**Comment by chobits** [comment]
Note that `ngx_http_null_variable` depends on nginx-1.13+.
